export const GET_ALL_PRODUCTS = "GET_ALL_PRODUCT";
export const GET_SINGLE_PRODUCTS = "GET_SINGLE_PRODUCT";
export const ADD_TO_CART = "ADD_TO_CART";
export const REMOVE_FROM_CART = "REMOVE_FROM_CART";
export const ADJUST_QTY = "ADJUST_QTY";
